language: java
sudo: false
os:
- linux
- osx
jdk: openjdk11
osx_image: xcode10.1
dist: xenial
before_install: bash CI/env_setup.sh
script:
- "./gradlew buildGhidra"
before_deploy:
- git config --local user.name "Anciety"
- git config --local user.email "anciety512@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)-${TRAVIS_OS_NAME}}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Ebk/wxyquFTPMm57Q+FFnOa98vMpVbREJnpprPfft4/yAL/PpKrx/RT9NwW8ccFw9E+OMYbwbeaZCF2l7xpxFRLvPMZ3RjoulU5y6vhXYmig3UD+rOeeyPB66ZoPtM6ELq3Mjvw403v+sL0HFzK/glj2iRh2R1CXgsR8gfseB/W7YZunoeNmZMNhIhzG45BcxsRLUQNf0dtwu1/ZS+kDpJHKtCyBH7OfCXRA6O5MXzXDDYQtibefm1qwTa6DFQnyIEmqXTi4xX+dLr856C9cVEKlNMKDETr3YgK5wUNq7ip2ostMqLyJ3+jK3DI45AxfwEgQaEgjTGW6OCMNax0aeUoLwTLazxDSaFu1nUtJOwUjrZj/47mwR8auJqUdtigQyKIo8j1DNkdaj0NW+DjJiONalXpvLjFnFkZoCnnBsKTlymS9XoNtZfGfZIJSOPMp+cKiBwJ0JjAfTgx3xIcF0IsSq5HAKcGpZb9/sXcl4IClFaNZEFtJLET9pqtN86TqquDg2wSCLTvTkJjrcl0kzkpxZZigaWToznboaI/6catJy4QbbtgfWjCV5x8SUv14mkXUHJ3IW6/ah9WkPwPKqogLhpJqsljMtdup1lKZiVXMbPGMK9CoD2NI5cYAA06oR42n8MIDbvFrwqx3HdIvRM8WnUvSjituzeL88Hz7Tgw=
  file: build/dist/*.zip
  on:
    repo: long-re/Long
