language: java
sudo: false
os:
- linux
- osx
jdk: openjdk11
osx_image: xcode10.1
dist: xenial
before_install: bash CI/env_setup.sh
script:
- "./gradlew buildGhidra"
before_deploy:
- git config --local user.name "Anciety"
- git config --local user.email "anciety512@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)-${TRAVIS_OS_NAME}}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN_SECURED}
  file: build/dist/*.zip
  file_glob: true
  on:
    branch: nightly-release
    repo: long-re/Long
