language: java
sudo: false

os:
  - linux
  - osx

jdk: openjdk11
osx_image: xcode10.1
dist: xenial

before_install: bash CI/env_setup.sh
script:
  - ./gradlew buildGhidra
   
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Anciety"
  - git config --local user.email "anciety512@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG 
deploy: 
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_OAUTH_TOKEN_SECURE
  file: "build/dist/*.zip"
  on:
    branch: nightly-release
